openapi: 3.0.0
info:
  title: Practica 1
  description: Esto es el backend de la practica 1
  contact:
    email: jlsn5@alu.ua.es
  version: 1.0.0
servers:
- url: http://localhost:8090/
  description: Servidor localhost
paths:
  /clientes:
    get:
      tags:
      - clientes
      summary: Get cliente
      description: get cliente
      operationId: clientesGET
      parameters:
      - name: id
        in: query
        description: hacer get cliente
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Invalid status value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-swagger-router-controller: Clientes
    post:
      tags:
      - clientes
      summary: Subir cliente
      description: Crear cliente
      operationId: postCliente
      requestBody:
        description: Crear nuevo cliente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        "405":
          description: Invalid input
      x-swagger-router-controller: Clientes
  /clientes/{clienteId}:
    put:
      tags:
      - clientes
      summary: Update cliente
      description: Actualizar cliente
      operationId: updateCliente
      parameters:
      - name: clienteId
        in: path
        description: Cliente para eliminar
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: actualiza cliente existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: Clientes
    delete:
      tags:
      - clientes
      summary: Borrar cliente
      description: Borra cliente por id
      operationId: deleteCliente
      parameters:
      - name: clienteId
        in: path
        description: Id de cliente a eliminar
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid pet value
      x-swagger-router-controller: Clientes
  /partes:
    get:
      tags:
      - partes
      summary: Get parte
      description: get parte
      operationId: partesGET
      parameters:
      - name: id
        in: query
        description: hacer get parte
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Invalid status value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-swagger-router-controller: Partes
    post:
      tags:
      - partes
      summary: Subir parte
      description: Crear cliente
      operationId: postParte
      requestBody:
        description: Crear nuevo cliente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parte'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parte'
        "405":
          description: Invalid input
      x-swagger-router-controller: Partes
  /partes/{parteId}:
    put:
      tags:
      - partes
      summary: Update parte
      description: Actualizar parte
      operationId: updateParte
      parameters:
      - name: parteId
        in: path
        description: Parte para eliminar
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: actualiza parte existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parte'
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: Partes
    delete:
      tags:
      - partes
      summary: Borrar parte
      description: Borra parte por id
      operationId: deleteParte
      parameters:
      - name: parteId
        in: path
        description: Id de parte a eliminar
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid pet value
      x-swagger-router-controller: Partes
components:
  schemas:
    Cliente:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
          example: Jose
        dni:
          type: string
          example: 12345678A
        direccion:
          type: string
          example: Calle Pizarro
        poblacion:
          type: string
          example: Alicante
        telefono:
          type: string
          example: "123456789"
        email:
          type: string
          example: usuario@gmail.com
      example:
        direccion: Calle Pizarro
        poblacion: Alicante
        telefono: "123456789"
        nombre: Jose
        dni: 12345678A
        email: usuario@gmail.com
    Parte:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fecha:
          type: string
          example: '2022-12-06T23:00:00.000Z'
        hora:
          type: string
          example: '10:10:10'
        descripcion:
          type: string
          example: Descripcion parte 1
        incidencia:
          type: boolean
          example: false
        tiempo:
          type: integer
          example: 123
        latitud:
          type: number
          example: 42
        longitud:
          type: number
          example: -24
      example:
        fecha: '2022-12-06T23:00:00.000Z'
        hora: '10:10:10'
        descripcion: Descripcion parte 1
        incidencia: false
        tiempo: 123
        latitud: 42
        longitud: -24
    inline_response_200:
      type: object
      properties:
        nombre:
          type: string
        contador:
          type: integer
      example:
        contador: 0
        nombre: nombre
    inline_response_400:
      type: object
      properties:
        message:
          type: string
